describe('planner weeks test', () => {
  it('passes', () => {
    cy.visit('http://127.0.0.1:8080')

    cy.get('[class="v-chip__content"]').contains("Log in").click()

    cy.get('[type="text"]').type('test')
    cy.get('[type="password"]').type('1234')
    cy.get('[class="v-btn__content"]').contains("Log In").click()

    cy.wait(2000)

    const dayjs = require('dayjs')
    const cur_date = dayjs().format('YYYY-MM-DD')

    cy.get('[class="v-list-item__title"]').contains('This week').should('exist')
    cy.get('[class="v-list-item__title"]').contains('This week').click()
    cy.get('[class="v-card v-sheet theme--light"]').contains(cur_date).should('exist')

    cy.get('[class="v-card v-sheet theme--light"]').contains('8:00 - 9:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('9:00 - 10:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('10:00 - 11:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('11:00 - 12:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('12:00 - 13:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('13:00 - 14:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('14:00 - 15:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('15:00 - 16:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('16:00 - 17:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('17:00 - 18:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('18:00 - 19:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('19:00 - 20:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('20:00 - 21:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('21:00 - 22:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('22:00 - 23:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('23:00 - 24:00').should('exist')


    cy.get('[class="v-list-item__title"]').contains('First week').should('exist')
    cy.get('[class="v-list-item__title"]').contains('First week').click()
    cy.get('span.v-btn__content').contains('[2023-04-24 - 2023-04-30]').should('exist')
    cy.get('span.v-btn__content').contains('[2023-04-24 - 2023-04-30]').parent('[class="v-btn v-btn--block v-btn--outlined theme--light v-size--small"]').should('exist')

    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-24').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-24').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-24').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Mon').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-25').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-25').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-25').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Tue').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-26').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-26').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-26').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Wed').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-27').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-27').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-27').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Thu').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-28').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-28').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-28').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Fri').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-29').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-29').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-29').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Sat').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-30').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-30').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-04-30').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Sun').should('exist')
    
    cy.get('[class="v-card v-sheet theme--light"]').contains('8:00 - 9:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('9:00 - 10:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('10:00 - 11:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('11:00 - 12:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('12:00 - 13:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('13:00 - 14:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('14:00 - 15:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('15:00 - 16:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('16:00 - 17:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('17:00 - 18:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('18:00 - 19:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('19:00 - 20:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('20:00 - 21:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('21:00 - 22:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('22:00 - 23:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('23:00 - 24:00').should('exist')


    cy.get('[class="v-list-item__title"]').contains('Last week').should('exist')
    cy.get('[class="v-list-item__title"]').contains('Last week').click()
    cy.get('span.v-btn__content').contains('[2023-07-31 - 2023-08-06]').should('exist')
    cy.get('span.v-btn__content').contains('[2023-07-31 - 2023-08-06]').parent('[class="v-btn v-btn--block v-btn--outlined theme--light v-size--small"]').should('exist')

    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-07-31').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-07-31').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-07-31').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Mon').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-01').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-01').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-01').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Tue').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-02').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-02').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-02').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Wed').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-03').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-03').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-03').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Thu').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-04').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-04').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-04').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Fri').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-05').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-05').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-05').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Sat').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-06').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-06').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-08-06').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Sun').should('exist')

    cy.get('[class="v-card v-sheet theme--light"]').contains('8:00 - 9:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('9:00 - 10:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('10:00 - 11:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('11:00 - 12:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('12:00 - 13:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('13:00 - 14:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('14:00 - 15:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('15:00 - 16:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('16:00 - 17:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('17:00 - 18:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('18:00 - 19:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('19:00 - 20:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('20:00 - 21:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('21:00 - 22:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('22:00 - 23:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('23:00 - 24:00').should('exist')
  })
})


describe('planner view test', () => {
  it('passes', () => {
    cy.visit('http://127.0.0.1:8080')

    cy.get('[class="v-chip__content"]').contains("Log in").click()

    cy.get('[type="text"]').type('test')
    cy.get('[type="password"]').type('1234')
    cy.get('[class="v-btn__content"]').contains("Log In").click()

    cy.wait(2000)

    cy.get('[class="v-list-item__title"]').contains('First week').click()

    cy.get('span.v-btn__content').contains('[2023-06-19 - 2023-06-25]').should('exist')
    cy.get('span.v-btn__content').contains('[2023-06-19 - 2023-06-25]').parent('[class="v-btn v-btn--block v-btn--outlined v-btn--text theme--light v-size--small"]').should('exist') 
    cy.get('span.v-btn__content').contains('[2023-06-19 - 2023-06-25]').click()
    
    cy.get('span.v-btn__content').contains('[2023-06-19 - 2023-06-25]').should('exist')
    cy.get('span.v-btn__content').contains('[2023-06-19 - 2023-06-25]').parent('[class="v-btn v-btn--block v-btn--outlined theme--light v-size--small"]').should('exist')

    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-19').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-19').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-19').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Mon').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-20').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-20').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-20').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Tue').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-21').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-21').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-21').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Wed').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-22').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-22').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-22').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Thu').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-23').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-23').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-23').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Fri').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-24').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-24').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-24').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Sat').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-25').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-25').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-06-25').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Sun').should('exist')

    cy.get('[class="v-card v-sheet theme--light"]').contains('8:00 - 9:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('9:00 - 10:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('10:00 - 11:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('11:00 - 12:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('12:00 - 13:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('13:00 - 14:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('14:00 - 15:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('15:00 - 16:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('16:00 - 17:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('17:00 - 18:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('18:00 - 19:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('19:00 - 20:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('20:00 - 21:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('21:00 - 22:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('22:00 - 23:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('23:00 - 24:00').should('exist')

    cy.get('[class="v-btn__content"]').contains('TEST1').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST1').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST1').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('have.css', 'background-color').and('eq', 'rgb(136, 255, 136)')

    cy.get('[class="v-btn__content"]').contains('TEST1').click()
    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Edit item').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').children('input').should('have.value', 'TEST1')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').children('textarea').should('have.value', 'TEST!!!!!')
    cy.get('[style="background: rgb(136, 255, 136);"]').should('exist')
    cy.get('[style="background: rgb(136, 255, 136);"]').children('[class="v-icon notranslate theme--light"]').should('exist')

    cy.get('[class="v-btn__content"]').contains('Delete').should('exist')
    cy.get('[class="v-btn__content"]').contains('Apply').should('exist')
    cy.get('[class="v-btn__content"]').contains('Cancel').should('exist')

    cy.get('[class="v-btn__content"]').contains('Cancel').click()


    cy.get('[class="v-btn__content"]').contains('TEST2').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST2').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST2').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('have.css', 'background-color').and('eq', 'rgb(136, 136, 255)')

    cy.get('[class="v-btn__content"]').contains('TEST2').click()
    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Edit item').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').children('input').should('have.value', 'TEST2')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').children('textarea').should('have.value', 'TEST 22222')
    cy.get('[style="background: rgb(136, 136, 255);"]').should('exist')
    cy.get('[style="background: rgb(136, 136, 255);"]').children('[class="v-icon notranslate theme--dark"]').should('exist')

    cy.get('[class="v-btn__content"]').contains('Delete').should('exist')
    cy.get('[class="v-btn__content"]').contains('Apply').should('exist')
    cy.get('[class="v-btn__content"]').contains('Cancel').should('exist')

    cy.get('[class="v-btn__content"]').contains('Cancel').click()


    cy.get('[class="v-btn__content"]').contains('TEST3').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST3').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST3').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('have.css', 'background-color').and('eq', 'rgb(255, 136, 136)')

    cy.get('[class="v-btn__content"]').contains('TEST3').click()
    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Edit item').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').children('input').should('have.value', 'TEST3')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').children('textarea').should('have.value', 'TEST  123')
    cy.get('[style="background: rgb(255, 136, 136);"]').should('exist')
    cy.get('[style="background: rgb(255, 136, 136);"]').children('[class="v-icon notranslate theme--dark"]').should('exist')

    cy.get('[class="v-btn__content"]').contains('Delete').should('exist')
    cy.get('[class="v-btn__content"]').contains('Apply').should('exist')
    cy.get('[class="v-btn__content"]').contains('Cancel').should('exist')

    cy.get('[class="v-btn__content"]').contains('Cancel').click()

  })
})

describe('planner create/clear test', () => {
  it('passes', () => {
    cy.visit('http://127.0.0.1:8080')

    cy.get('[class="v-chip__content"]').contains("Log in").click()

    cy.get('[type="text"]').type('test')
    cy.get('[type="password"]').type('1234')
    cy.get('[class="v-btn__content"]').contains("Log In").click()

    cy.wait(2000)

    cy.get('[class="v-list-item__title"]').contains('First week').click()
    
    cy.get('span.v-btn__content').contains('[2023-05-22 - 2023-05-28]').should('exist')
    cy.get('span.v-btn__content').contains('[2023-05-22 - 2023-05-28]').parent('[class="v-btn v-btn--block v-btn--outlined v-btn--text theme--light v-size--small"]').should('exist') 
    cy.get('span.v-btn__content').contains('[2023-05-22 - 2023-05-28]').click()
    
    cy.get('span.v-btn__content').contains('[2023-05-22 - 2023-05-28]').should('exist')
    cy.get('span.v-btn__content').contains('[2023-05-22 - 2023-05-28]').parent('[class="v-btn v-btn--block v-btn--outlined theme--light v-size--small"]').should('exist')

    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-22').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-22').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-22').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Mon').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-23').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-23').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-23').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Tue').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-24').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-24').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-24').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Wed').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-25').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-25').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-25').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Thu').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-26').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-26').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-26').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Fri').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-27').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-27').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-27').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Sat').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-28').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-28').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-28').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Sun').should('exist')

    cy.get('[class="v-card v-sheet theme--light"]').contains('8:00 - 9:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('9:00 - 10:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('10:00 - 11:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('11:00 - 12:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('12:00 - 13:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('13:00 - 14:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('14:00 - 15:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('15:00 - 16:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('16:00 - 17:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('17:00 - 18:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('18:00 - 19:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('19:00 - 20:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('20:00 - 21:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('21:00 - 22:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('22:00 - 23:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('23:00 - 24:00').should('exist')

    cy.wait(2000)

    cy.get('[class="v-btn__content"]').contains('TEST A').should('not.exist')
    cy.get('[class="v-btn__content"]').contains('-').first().click()

    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Create new item').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Title').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').children('input').type("TEST A")
    cy.get('[class="v-label theme--light"]').contains('Text').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').children('textarea').type("Test ABCDEFGHIJ")
    cy.get('[style="background: rgb(136, 255, 255);"]').should('exist')
    cy.get('[style="background: rgb(136, 255, 255);"]').click()

    cy.get('[class="v-btn__content"]').contains('Delete').should('not.exist')
    cy.get('[class="v-btn__content"]').contains('Apply').should('exist')
    cy.get('[class="v-btn__content"]').contains('Cancel').should('exist')

    cy.get('[class="v-btn__content"]').contains('Apply').click()
    cy.get('[class="v-btn__content"]').contains('TEST A').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST A').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST A').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('have.css', 'background-color').and('eq', 'rgb(136, 255, 255)')



    cy.get('[class="v-btn__content"]').contains('TEST B').should('not.exist')
    cy.get('[class="v-btn__content"]').contains('-').first().click()

    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Create new item').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Title').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').children('input').type("TEST B")
    cy.get('[class="v-label theme--light"]').contains('Text').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').children('textarea').type("Test 1234567890")
    cy.get('[style="background: rgb(255, 170, 204);"]').should('exist')
    cy.get('[style="background: rgb(255, 170, 204);"]').click()

    cy.get('[class="v-btn__content"]').contains('Delete').should('not.exist')
    cy.get('[class="v-btn__content"]').contains('Apply').should('exist')
    cy.get('[class="v-btn__content"]').contains('Cancel').should('exist')

    cy.get('[class="v-btn__content"]').contains('Cancel').click()
    cy.get('[class="v-btn__content"]').contains('TEST B').should('not.exist')
    cy.get('[class="v-btn__content"]').contains('-').first().click()

    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Create new item').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Title').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').children('input').type("TEST B")
    cy.get('[class="v-label theme--light"]').contains('Text').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').children('textarea').type("Test 1234567890")
    cy.get('[style="background: rgb(255, 170, 204);"]').should('exist')
    cy.get('[style="background: rgb(255, 170, 204);"]').click()

    cy.get('[class="v-btn__content"]').contains('Delete').should('not.exist')
    cy.get('[class="v-btn__content"]').contains('Apply').should('exist')
    cy.get('[class="v-btn__content"]').contains('Cancel').should('exist')

    cy.get('[class="v-btn__content"]').contains('Apply').click()
    cy.get('[class="v-btn__content"]').contains('TEST B').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST B').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST B').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('have.css', 'background-color').and('eq', 'rgb(255, 170, 204)')
    
    cy.get('[class="v-btn__content"]').contains('TEST C').should('not.exist')
    cy.get('[class="v-btn__content"]').contains('-').first().click()

    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Create new item').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Title').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').children('input').type("TEST C")
    cy.get('[class="v-label theme--light"]').contains('Text').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').children('textarea').type("Test qwerty")
    cy.get('[style="background: rgb(255, 204, 170);"]').should('exist')
    cy.get('[style="background: rgb(255, 204, 170);"]').click()

    cy.get('[class="v-btn__content"]').contains('Delete').should('not.exist')
    cy.get('[class="v-btn__content"]').contains('Apply').should('exist')
    cy.get('[class="v-btn__content"]').contains('Cancel').should('exist')

    cy.get('[class="v-btn__content"]').contains('Apply').click()
    cy.get('[class="v-btn__content"]').contains('TEST C').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST C').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST C').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('have.css', 'background-color').and('eq', 'rgb(255, 204, 170)')

    
    cy.get('[class="v-list-item__title"]').contains('Clear week').click()

    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Are you sure to delete all items of this week?').should('exist')
    cy.get('[class="v-card__text"]').contains('The data will be lost').should('exist')
    cy.get('[class="v-btn__content"]').contains('Yes, delete').should('exist')
    cy.get('[class="v-btn__content"]').contains('No, cancel').should('exist')

    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Are you sure to delete all items of this week?').should('be.visible')
    cy.get('[class="v-card__text"]').contains('The data will be lost').should('be.visible')
    cy.get('[class="v-btn__content"]').contains('Yes, delete').should('be.visible')
    cy.get('[class="v-btn__content"]').contains('No, cancel').should('be.visible')

    cy.get('[class="v-btn__content"]').contains('No, cancel').last().click()

    cy.get('[class="v-btn__content"]').contains('TEST A').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST B').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST C').should('exist')


    cy.get('[class="v-list-item__title"]').contains('Clear week').click()

    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Are you sure to delete all items of this week?').should('exist')
    cy.get('[class="v-card__text"]').contains('The data will be lost').should('exist')
    cy.get('[class="v-btn__content"]').contains('Yes, delete').should('exist')
    cy.get('[class="v-btn__content"]').contains('No, cancel').should('exist')

    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Are you sure to delete all items of this week?').should('be.visible')
    cy.get('[class="v-card__text"]').contains('The data will be lost').should('be.visible')
    cy.get('[class="v-btn__content"]').contains('Yes, delete').should('be.visible')
    cy.get('[class="v-btn__content"]').contains('No, cancel').should('be.visible')

    cy.get('[class="v-btn__content"]').contains('Yes, delete').last().click()

    cy.get('[class="v-btn__content"]').contains('TEST A').should('not.exist')
    cy.get('[class="v-btn__content"]').contains('TEST B').should('not.exist')
    cy.get('[class="v-btn__content"]').contains('TEST C').should('not.exist')
  })
})

describe('planner create/delete test', () => {
  it('passes', () => {
    cy.visit('http://127.0.0.1:8080')

    cy.get('[class="v-chip__content"]').contains("Log in").click()

    cy.get('[type="text"]').type('test')
    cy.get('[type="password"]').type('1234')
    cy.get('[class="v-btn__content"]').contains("Log In").click()

    cy.wait(2000)

    cy.get('[class="v-list-item__title"]').contains('First week').click()
    
    cy.get('span.v-btn__content').contains('[2023-05-22 - 2023-05-28]').should('exist')
    cy.get('span.v-btn__content').contains('[2023-05-22 - 2023-05-28]').parent('[class="v-btn v-btn--block v-btn--outlined v-btn--text theme--light v-size--small"]').should('exist') 
    cy.get('span.v-btn__content').contains('[2023-05-22 - 2023-05-28]').click()
    
    cy.get('span.v-btn__content').contains('[2023-05-22 - 2023-05-28]').should('exist')
    cy.get('span.v-btn__content').contains('[2023-05-22 - 2023-05-28]').parent('[class="v-btn v-btn--block v-btn--outlined theme--light v-size--small"]').should('exist')

    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-22').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-22').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-22').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Mon').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-23').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-23').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-23').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Tue').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-24').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-24').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-24').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Wed').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-25').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-25').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-25').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Thu').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-26').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-26').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-26').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Fri').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-27').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-27').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-27').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Sat').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-28').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-28').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-28').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Sun').should('exist')

    cy.get('[class="v-card v-sheet theme--light"]').contains('8:00 - 9:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('9:00 - 10:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('10:00 - 11:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('11:00 - 12:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('12:00 - 13:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('13:00 - 14:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('14:00 - 15:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('15:00 - 16:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('16:00 - 17:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('17:00 - 18:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('18:00 - 19:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('19:00 - 20:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('20:00 - 21:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('21:00 - 22:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('22:00 - 23:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('23:00 - 24:00').should('exist')

    cy.wait(2000)

    cy.get('[class="v-btn__content"]').contains('TEST A').should('not.exist')
    cy.get('[class="v-btn__content"]').contains('-').first().click()

    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Create new item').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Title').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').children('input').type("TEST A")
    cy.get('[class="v-label theme--light"]').contains('Text').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').children('textarea').type("Test ABCDEFGHIJ")
    cy.get('[style="background: rgb(136, 255, 255);"]').should('exist')
    cy.get('[style="background: rgb(136, 255, 255);"]').click()

    cy.get('[class="v-btn__content"]').contains('Delete').should('not.exist')
    cy.get('[class="v-btn__content"]').contains('Apply').should('exist')
    cy.get('[class="v-btn__content"]').contains('Cancel').should('exist')

    cy.get('[class="v-btn__content"]').contains('Apply').click()
    cy.get('[class="v-btn__content"]').contains('TEST A').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST A').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST A').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('have.css', 'background-color').and('eq', 'rgb(136, 255, 255)')

    cy.get('[class="v-btn__content"]').contains('TEST A').click()
    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Edit item').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').children('input').should('have.value', 'TEST A')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').children('textarea').should('have.value', 'Test ABCDEFGHIJ')

    cy.get('[class="v-btn__content"]').contains('Delete').should('exist')
    cy.get('[class="v-btn__content"]').contains('Delete').should('be.visible')
    cy.get('[class="v-btn__content"]').contains('Delete').click()

    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Are you sure to delete item?').should('exist')
    cy.get('[class="v-btn__content"]').contains('Yes, delete').should('exist')
    cy.get('[class="v-btn__content"]').contains('No, cancel').should('exist')

    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Are you sure to delete item?').should('be.visible')
    cy.get('[class="v-btn__content"]').contains('Yes, delete').should('be.visible')
    cy.get('[class="v-btn__content"]').contains('No, cancel').should('be.visible')

    cy.get('[class="v-btn__content"]').contains('No, cancel').click()
    cy.get('[class="v-btn__content"]').contains('TEST A').should('exist')

    cy.get('[class="v-btn__content"]').contains('Delete').should('exist')
    cy.get('[class="v-btn__content"]').contains('Delete').should('be.visible')
    cy.get('[class="v-btn__content"]').contains('Delete').click()

    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Are you sure to delete item?').should('exist')
    cy.get('[class="v-btn__content"]').contains('Yes, delete').should('exist')
    cy.get('[class="v-btn__content"]').contains('No, cancel').should('exist')

    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Are you sure to delete item?').should('be.visible')
    cy.get('[class="v-btn__content"]').contains('Yes, delete').should('be.visible')
    cy.get('[class="v-btn__content"]').contains('No, cancel').should('be.visible')

    cy.get('[class="v-btn__content"]').contains('Yes, delete').click()
    cy.get('[class="v-btn__content"]').contains('TEST A').should('not.exist')
  })
})


describe('planner edit test', () => {
  it('passes', () => {
    cy.visit('http://127.0.0.1:8080')

    cy.get('[class="v-chip__content"]').contains("Log in").click()

    cy.get('[type="text"]').type('test')
    cy.get('[type="password"]').type('1234')
    cy.get('[class="v-btn__content"]').contains("Log In").click()

    cy.wait(2000)

    cy.get('[class="v-list-item__title"]').contains('First week').click()
    
    cy.get('span.v-btn__content').contains('[2023-05-01 - 2023-05-07]').should('exist')
    cy.get('span.v-btn__content').contains('[2023-05-01 - 2023-05-07]').parent('[class="v-btn v-btn--block v-btn--outlined v-btn--text theme--light v-size--small"]').should('exist') 
    cy.get('span.v-btn__content').contains('[2023-05-01 - 2023-05-07]').click()
    
    cy.get('span.v-btn__content').contains('[2023-05-01 - 2023-05-07]').should('exist')
    cy.get('span.v-btn__content').contains('[2023-05-01 - 2023-05-07]').parent('[class="v-btn v-btn--block v-btn--outlined theme--light v-size--small"]').should('exist')

    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-01').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-01').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-01').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Mon').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-02').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-02').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-02').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Tue').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-03').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-03').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-03').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Wed').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-04').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-04').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-04').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Thu').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-05').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-05').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-05').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Fri').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-06').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-06').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-06').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Sat').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-07').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-07').parent('[class="v-card v-sheet theme--light elevation-2"]').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('2023-05-07').parent('[class="v-card v-sheet theme--light elevation-2"]').children('[class="v-card v-sheet theme--light"]').contains('Sun').should('exist')

    cy.get('[class="v-card v-sheet theme--light"]').contains('8:00 - 9:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('9:00 - 10:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('10:00 - 11:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('11:00 - 12:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('12:00 - 13:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('13:00 - 14:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('14:00 - 15:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('15:00 - 16:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('16:00 - 17:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('17:00 - 18:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('18:00 - 19:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('19:00 - 20:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('20:00 - 21:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('21:00 - 22:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('22:00 - 23:00').should('exist')
    cy.get('[class="v-card v-sheet theme--light"]').contains('23:00 - 24:00').should('exist')

    cy.wait(2000)

    cy.get('[class="v-btn__content"]').contains('TEST E').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST E').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST E').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('have.css', 'background-color').and('eq', 'rgb(204, 204, 255)')

    cy.get('[class="v-btn__content"]').contains('TEST E').click()
    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Edit item').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').children('input').should('have.value', 'TEST E')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').children('textarea').should('have.value', 'Test Test Test')
    cy.get('[style="background: rgb(204, 204, 255);"]').should('exist')
    cy.get('[style="background: rgb(204, 204, 255);"]').children('[class="v-icon notranslate theme--light"]').should('exist')

    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').children('input').type('{selectall}{backspace}TEST *')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').children('textarea').type('{selectall}{backspace}Test X3')
    cy.get('[style="background: rgb(204, 255, 204);"]').should('exist')
    cy.get('[style="background: rgb(204, 255, 204);"]').last().click()

    cy.get('[class="v-btn__content"]').contains('Delete').should('exist')
    cy.get('[class="v-btn__content"]').contains('Apply').should('exist')
    cy.get('[class="v-btn__content"]').contains('Cancel').should('exist')

    cy.get('[class="v-btn__content"]').contains('Delete').should('be.visible')
    cy.get('[class="v-btn__content"]').contains('Apply').should('be.visible')
    cy.get('[class="v-btn__content"]').contains('Cancel').should('be.visible')

    cy.get('[class="v-btn__content"]').contains('Apply').first().click()
    cy.get('[class="v-btn__content"]').contains('TEST E').should('not.exist')
    cy.get('[class="v-btn__content"]').contains('TEST *').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST *').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST *').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('have.css', 'background-color').and('eq', 'rgb(204, 255, 204)')
 


    cy.get('[class="v-btn__content"]').contains('TEST *').click()
    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Edit item').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').children('input').should('have.value', 'TEST *')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').children('textarea').should('have.value', 'Test X3')
    cy.get('[style="background: rgb(204, 255, 204);"]').should('exist')
    cy.get('[style="background: rgb(204, 255, 204);"]').children('[class="v-icon notranslate theme--light"]').should('exist')

    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').children('input').type('{selectall}{backspace}TEST #')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').children('textarea').type('{selectall}{backspace}Test #######')
    cy.get('[style="background: rgb(255, 204, 204);"]').should('exist')
    cy.get('[style="background: rgb(255, 204, 204);"]').last().click()

    cy.get('[class="v-btn__content"]').contains('Delete').should('exist')
    cy.get('[class="v-btn__content"]').contains('Apply').should('exist')
    cy.get('[class="v-btn__content"]').contains('Cancel').should('exist')

    cy.get('[class="v-btn__content"]').contains('Delete').should('be.visible')
    cy.get('[class="v-btn__content"]').contains('Apply').should('be.visible')
    cy.get('[class="v-btn__content"]').contains('Cancel').should('be.visible')

    cy.get('[class="v-btn__content"]').contains('Cancel').first().click()
    cy.get('[class="v-btn__content"]').contains('TEST E').should('not.exist')
    cy.get('[class="v-btn__content"]').contains('TEST *').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST *').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST *').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('have.css', 'background-color').and('eq', 'rgb(204, 255, 204)')



    cy.get('[class="v-btn__content"]').contains('TEST *').click()
    cy.get('[class="v-card__title text-h5 grey lighten-2"]').contains('Edit item').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').children('input').should('have.value', 'TEST *')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').should('exist')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').children('textarea').should('have.value', 'Test X3')
    cy.get('[style="background: rgb(204, 255, 204);"]').should('exist')
    cy.get('[style="background: rgb(204, 255, 204);"]').children('[class="v-icon notranslate theme--light"]').should('exist')

    cy.get('[class="v-label v-label--active theme--light"]').contains('Title').parent('[class="v-text-field__slot"]').children('input').type('{selectall}{backspace}TEST E')
    cy.get('[class="v-label v-label--active theme--light"]').contains('Text').parent('[class="v-text-field__slot"]').children('textarea').type('{selectall}{backspace}Test Test Test')
    cy.get('[style="background: rgb(204, 204, 255);"]').should('exist')
    cy.get('[style="background: rgb(204, 204, 255);"]').last().click()

    cy.get('[class="v-btn__content"]').contains('Delete').should('exist')
    cy.get('[class="v-btn__content"]').contains('Apply').should('exist')
    cy.get('[class="v-btn__content"]').contains('Cancel').should('exist')

    cy.get('[class="v-btn__content"]').contains('Delete').should('be.visible')
    cy.get('[class="v-btn__content"]').contains('Apply').should('be.visible')
    cy.get('[class="v-btn__content"]').contains('Cancel').should('be.visible')

    cy.get('[class="v-btn__content"]').contains('Apply').first().click()
    cy.get('[class="v-btn__content"]').contains('TEST *').should('not.exist')
    cy.get('[class="v-btn__content"]').contains('TEST E').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST E').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('exist')
    cy.get('[class="v-btn__content"]').contains('TEST E').parent('[class="v-btn v-btn--block v-btn--is-elevated v-btn--has-bg v-btn--rounded theme--light v-size--small"]').should('have.css', 'background-color').and('eq', 'rgb(204, 204, 255)')
  
  })
})